### ISSUE TITLE
关于里站h萌娘

### ISSUE THREAD

**Issue by 850710247liu** [koharubiyori/Moegirl-RN#3]
是否有想法在软件中写入到h萌娘的一些模块（或者写个h萌娘客户端）

**Comment by koharubiyori** [comment]
emmm，目前这个项目当前版本已经暂定为终版了，因为mediawiki接口返回的数据好多都是html的，实在是不适合用原生渲染。最近正在着手使用ionic进行重构。届时打算提供一个更换数据源url的参数用来支持h萌的浏览，直接给h萌的入口估计多半会被下架。

**Comment by 850710247liu** [comment]
thank you
