### ISSUE TITLE
验证问题

### ISSUE THREAD

**Issue by 850710247liu** [koharubiyori/Moegirl-RN#4]
有时候使用梯子登陆时需要先验证，如图https://imgchr.com/i/3K2R1K
，然而app直接显示读取失败，无法使用

**Comment by 850710247liu** [comment]
还有希望改一下项目名和默认使用h萌娘数据源和皮肤，我想作为h萌娘客户端在首页推一下（滑稽），这个不着急，多谢大佬了❤

**Comment by koharubiyori** [comment]
1. 登录那个问题不好调试，我尽量想办法修复。主要是不知道什么时候要验证什么时候不需要，我这里测试梯子换了好几个节点都没出现需要人机验证的情况。
1. 改名我认为不是很妥当，github上的这个版本是作为moegirlViewer的另一个版本发布的，改了名就成另外一个app了。默认数据源和皮肤可以修改。
1. 如果要在h萌首页上推还是先联系一下萌百的管理人员吧，毕竟我不是萌百官方。

**Comment by 850710247liu** [comment]
能告诉我你用的是什么梯子吗（不需要节点）

**Comment by 850710247liu** [comment]
能告诉我你用的是什么梯子吗（不需要验证的），我用的是免费的老王vp

**Comment by 850710247liu** [comment]
h

**Comment by 850710247liu** [comment]
能告诉我你用的是什么tizi吗（不需要验证的），我用的是免费的老王 upn

**Comment by koharubiyori** [comment]
平时用自己搭的，上需要原生日本ip才能访问的网站时用这个：https://aaex.uk/cart.php，以前有无时限流量套餐的时候买了300GB，现在这个梯子的套餐都比较贵。

**Comment by koharubiyori** [comment]
我也不知道到底什么条件下会触发验证机制

**Comment by 850710247liu** [comment]
你用过shadowsocks吗，当时free-ss.site那里的也需要验证，好像免费的谁都用那种几乎都是验证，三年没花一分钱的我上h萌一直都得认证

**Comment by 850710247liu** [comment]
触发机制应该是首次连接，认证成功就不会出现，但断网重连还会出现

**Comment by koharubiyori** [comment]
感觉应该还是和服务提供者有关系，我自己搭的是v2ray，aaex那个是shadowsocks，都没出现过需要验证的情况。每次首次连接需要验证应该是session(可以理解为在服务端暂存的凭证，用户长时间离开就会自动销毁)过期了。不过话说回来需要验证的问题肯定是要解决的，不能指望用户都用不需要验证的梯子，我一会看看能不能找个免费帐号试试

**Comment by koharubiyori** [comment]
也可以试试我搭的梯子，Vultr东京的机房（但在谷歌上显示是菲律宾），流量的话姑且不限吧（只要别一个月走500G流量什么的就行） 。当然肯定不是免费的，10块钱一个月

**Comment by 850710247liu** [comment]
高考后我会考虑的，目前在备考阶段，黑龙江疫情太严重了，和湖北快差不多了，我们下个月都开不了学，一直网上教学，今年分肯定低，但不知道明年我考咋样😭

**Comment by 850710247liu** [comment]
对了，那个linksshow能识别分类里的条目进行展示吗，我想把那个li番专题模板指向的分类:里番用上linksshow（因为正好20个条目）

**Comment by koharubiyori** [comment]
不能，所有动态的内容都是不能经过再次处理的

**Comment by 850710247liu** [comment]
Thank you, <s>看来只能靠我挑着输了</s>

**Comment by 850710247liu** [comment]
实际上那个api登陆可以这样调试，让程序先尝试访问谷歌看是否返回数据以确定是否连接到外网，然后看h萌娘是否传回了错误的数据，要是就直接打开，就是验证界面

**Comment by koharubiyori** [comment]
感谢你提供的方案，其实前天我在提问求助区已经了解到带验证登录的基本流程了，但还是没办法测试

**Comment by 850710247liu** [comment]
没事，等疫情过去的吧，祝你好运😄
