### ISSUE TITLE
一些bug反馈

### ISSUE THREAD

**Issue by 850710247liu** [koharubiyori/Moegirl-RN#5]
换了个荷兰的节点，能够正常使用了，有些bug反馈一下
1.首页只显示了4个模块，还有些没显示
2.首页优质条目推荐的那个图片轮播不起作用了
3.首页里主题模块的那个更多主题那页图片显示乱了
4.趋势里可以不写mainpage，还有一些重了
5.搜索框的灰字应该从搜索萌娘百科改为搜索H萌娘

**Comment by koharubiyori** [comment]
1. 有些模块是故意隐藏的，因为其中的特殊链接(以Special: 或 特殊: 开头的)暂时还未适配
1. 我这边拿到的只是html字符串，轮播效果需要自己实现，但是我现在没法总开着h萌_(:з」∠)_ 
1. 现在h萌还有很多页面有问题，原因还是同上，以后会修复的
1. 4，5下版本修复。

感谢反馈！
